# Note: Rename the word 'example' to your project name in lowercase
services:
  postgres-dev:
    image: postgres:17.2
    container_name: example-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - example-network

  redis-dev:
    image: valkey/valkey:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - example-network

volumes:
  postgres_data_dev:

networks:
  example-network:
    driver: bridge
